In [15]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras import initializers
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from deap import algorithms, base, creator, tools

df = pd.read_csv('/Users/cra/Downloads/Bank_Personal_Loan_Modelling.csv')

df = df[['Age', 'Experience', 'Income', 'Family', 'CCAvg',
         'Education', 'Mortgage', 'Securities Account', 'CD Account',
         'Online', 'CreditCard', 'Personal Loan']]

In [16]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=104, test_size=0.25)


In [4]:
model = Sequential()
model.add(Dense(4, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(1, activation='sigmoid', kernel_initializer=initializers.Zeros()))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=20, batch_size=1)

Epoch 1/20


2023-04-05 14:53:56.495282: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


3750/3750 [==============================] - 1s 315us/step - loss: 0.2841 - accuracy: 0.9000
Epoch 2/20
3750/3750 [==============================] - 1s 320us/step - loss: 0.2278 - accuracy: 0.9035
Epoch 3/20
3750/3750 [==============================] - 1s 327us/step - loss: 0.2154 - accuracy: 0.9035
Epoch 4/20
3750/3750 [==============================] - 1s 312us/step - loss: 0.2127 - accuracy: 0.9040
Epoch 5/20
3750/3750 [==============================] - 1s 307us/step - loss: 0.2069 - accuracy: 0.9040
Epoch 6/20
3750/3750 [==============================] - 1s 317us/step - loss: 0.2084 - accuracy: 0.9040
Epoch 7/20
3750/3750 [==============================] - 1s 351us/step - loss: 0.2060 - accuracy: 0.9040
Epoch 8/20
3750/3750 [==============================] - 1s 322us/step - loss: 0.2038 - accuracy: 0.9035
Epoch 9/20
3750/3750 [==============================] - 1s 317us/step - loss: 0.2002 - accuracy: 0.9040
Epoch 10/20
3750/3750 [==============================] - 2s 437us/step - lo

In [17]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.2).astype(int)
print(classification_report(y_test, y_pred))

weights = model.get_weights()

# Print the weights of the first layer
print(weights[0])

# Print the weights of the second layer
print(weights[2])

40/40 [==============================] - 0s 317us/step
              precision    recall  f1-score   support

           0       0.98      0.90      0.94      1130
           1       0.47      0.83      0.60       120

    accuracy                           0.89      1250
   macro avg       0.73      0.87      0.77      1250
weighted avg       0.93      0.89      0.91      1250

[[-1.11326145e-35  5.48254251e-01 -4.79594899e-34 -3.43734697e-02]
 [-2.74892981e-34 -4.96152341e-01  9.19278654e-35  7.36692622e-02]
 [ 4.08771870e-34 -1.13723852e-01  4.89171459e-34  7.05378279e-02]
 [-5.24894962e-36 -2.96764318e-02 -3.57398290e-34  1.23712271e-01]
 [-1.08136664e-34 -4.66635197e-01 -5.27051581e-34  2.32722168e-03]
 [-4.31852013e-34 -1.30992636e-01  3.57313089e-34  1.32996038e-01]
 [ 1.13172360e-34  9.86220036e-03  2.98373252e-34  3.06555536e-02]
 [ 5.31542382e-34 -3.72373015e-02 -1.17534741e-34  8.99466779e-03]
 [ 4.95697886e-34 -9.56067666e-02  5.11257023e-34  3.32246833e-02]
 [-3.29765838e-

In [8]:
from keras import regularizers
from keras.optimizers import Adam

# Define the neural network architecture with L2 regularization in the first layer
model = Sequential()
model.add(Dense(4, input_dim=X_train.shape[1], activation='relu', kernel_regularizer=regularizers.l2(0.01)))
model.add(Dense(1, activation='sigmoid', kernel_initializer=initializers.Zeros()))

# Compile the model with the Adam optimizer and a learning rate of 0.001
optimizer = Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

# Train the model with L2 regularization
model.fit(X_train, y_train, epochs=20, batch_size=1, validation_data=(X_test, y_test))


Epoch 1/20
3750/3750 [==============================] - 2s 446us/step - loss: 0.2960 - accuracy: 0.9013 - val_loss: 0.2465 - val_accuracy: 0.9040
Epoch 2/20
3750/3750 [==============================] - 2s 408us/step - loss: 0.2465 - accuracy: 0.9016 - val_loss: 0.2288 - val_accuracy: 0.9040
Epoch 3/20
3750/3750 [==============================] - 1s 396us/step - loss: 0.2309 - accuracy: 0.9037 - val_loss: 0.2232 - val_accuracy: 0.9040
Epoch 4/20
3750/3750 [==============================] - 1s 399us/step - loss: 0.2236 - accuracy: 0.9027 - val_loss: 0.2000 - val_accuracy: 0.9040
Epoch 5/20
3750/3750 [==============================] - 1s 393us/step - loss: 0.2172 - accuracy: 0.9032 - val_loss: 0.2025 - val_accuracy: 0.9040
Epoch 6/20
3750/3750 [==============================] - 2s 414us/step - loss: 0.2121 - accuracy: 0.9032 - val_loss: 0.2051 - val_accuracy: 0.9040
Epoch 7/20
3750/3750 [==============================] - 2s 403us/step - loss: 0.2093 - accuracy: 0.9040 - val_loss: 0.1921 -

In [22]:
from keras import backend as K
import random
def fitness_func(weights):
    model.set_weights(weights)
    loss, accuracy = model.evaluate(X_train, y_train, verbose=0)
    return accuracy,

# Define the genetic algorithm parameters
POPULATION_SIZE = 20
PARENTS_PERCENTAGE = 0.5
MUTATION_PERCENTAGE = 0.2
GENERATIONS = 10

# Define the genetic algorithm functions
def create_individual():
    weights = []
    for layer in model.layers:
        shape = layer.get_weights()[0].shape
        biases_shape = layer.get_weights()[1].shape
        w = np.random.randn(*shape)
        b = np.random.randn(*biases_shape)
        weights.append(w)
        weights.append(b)
    return np.array(weights)

def crossover(parent_1, parent_2):
    child = []
    for i in range(len(parent_1)):
        if random.random() < 0.5:
            child.append(parent_1[i])
        else:
            child.append(parent_2[i])
    return np.array(child)

def mutate(individual):
    for i in range(len(individual)):
        if random.random() < MUTATION_PERCENTAGE:
            shape = individual[i].shape
            individual[i] += np.random.randn(*shape) * 0.1
    return individual

# Define the main function to run the genetic algorithm
def main():
    population = [create_individual() for _ in range(POPULATION_SIZE)]
    for generation in range(GENERATIONS):
        print("Generation", generation+1)
        fitness_scores = []
        for individual in population:
            fitness_scores.append((individual, fitness_func(individual)))
        fitness_scores = sorted(fitness_scores, key=lambda x: x[1], reverse=True)
        print("Best individual:", fitness_scores[0][1])
        parents = [x[0] for x in fitness_scores[:int(len(population)*PARENTS_PERCENTAGE)]]
        new_population = parents[:]
        for _ in range(int(len(population)*PARENTS_PERCENTAGE), POPULATION_SIZE):
            parent_1 = random.choice(parents)
            parent_2 = random.choice(parents)
            child = crossover(parent_1, parent_2)
            child = mutate(child)
            new_population.append(child)
        population = new_population
    best_individual = fitness_scores[0][0]
    model.set_weights(best_individual)
main()

/var/folders/5d/55480rsn6f9b9207_fgt7cgw0000gn/T/ipykernel_76600/1260059021.py:24: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(weights)


Generation 1
Best individual: (0.9039999842643738,)
Generation 2


/var/folders/5d/55480rsn6f9b9207_fgt7cgw0000gn/T/ipykernel_76600/1260059021.py:33: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(child)


Best individual: (0.9039999842643738,)
Generation 3
Best individual: (0.9039999842643738,)
Generation 4
Best individual: (0.9039999842643738,)
Generation 5
Best individual: (0.9039999842643738,)
Generation 6
Best individual: (0.9039999842643738,)
Generation 7
Best individual: (0.9039999842643738,)
Generation 8
Best individual: (0.9039999842643738,)
Generation 9
Best individual: (0.9039999842643738,)
Generation 10
Best individual: (0.9039999842643738,)


In [24]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from pyeasyga import CulturalEvolutionaryAlgorithm
import numpy as np

# Define the fitness function
def evaluate(individual):
    # Set the weights for the neural network
    model.set_weights(individual)
    
    # Train the model
    model.fit(X_train, y_train, epochs=20, batch_size=1, verbose=0)
    
    # Evaluate the model on the test set
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, np.round(y_pred))
    
    # Return the negative accuracy as the fitness (since CEA minimizes the fitness)
    return -accuracy,

# Load the dataset
df = pd.read_csv(r'/Users/cra/Downloads/Bank_Personal_Loan_Modelling.csv')
df = df[['Age', 'Experience', 'Income', 'Family', 'CCAvg','Education', 'Mortgage', 'Securities Account','CD Account', 'Online', 'CreditCard', 'Personal Loan']]
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=104, test_size=0.25)

# Create the neural network model
model = Sequential()
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Set up the cultural evolutionary algorithm
cea = CulturalEvolutionaryAlgorithm(individual_size=model.count_params(),
                                    evaluation_function=evaluate,
                                    population_size=20,
                                    generation_count=50,
                                    belief_space_size=5,
                                    communication_probability=0.5,
                                    exploration_probability=0.5)

# Run the optimization process
best_weights, best_fitness = cea.evolve()

# Set the best weights to the neural network
model.set_weights(best_weights)

# Train the neural network with the best weights
model.fit(X_train, y_train, epochs=20, batch_size=1, verbose=0)

# Evaluate the accuracy of the neural network with the best weights
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, np.round(y_pred))

print("Best fitness:", best_fitness)
print("Accuracy with best weights:", accuracy)


ModuleNotFoundError: No module named 'cpea'